13 [8.0 PT] - Create Reservation functionalities on the backend
kamzzy/Hotel-Room pull request #43
Opened 2022-10-10 17:52 UTC by felixodette

- Create the ‘Reservation’ model and attributes are (date, room_id, user_id[From LocalStorage])
- Add Belongs_to User, belongs_to Room
- #create, #index actions will be used in controller
- Add view

2022-10-10 18:17 UTC, huseyinbiyik requested changes
## Required Changes ♻️
## Hi @felixodette , 
 ### You have been doing a tremendous job so far :ok_hand:

## To Improve 🙏
- Please check the inline comments under the review

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.

2022-10-10 18:21 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
We don't need all the reservations in the database but we only need User's reservations listed on the front end according to the the instructions https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#:~:text=When%20the%20user%20clicks%20the%20%22My%20reservations%22%20link%20in%20the%20navigation%20panel%20they%20can%20see%20a%20list%20of%20their%20reservations%20(with%20information%20about%20item%20name%2C%20date%20and%20city). Kindly fix the index function or do you have a different approach?

2022-10-10 18:24 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
According to the instructions we don't need any show page for the reservations component we only list them or add one with a form. I need your clarification on this part. I might be missing something could you help me to understand it?

2022-10-10 18:29 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
The start and end dates really make sense but I am not sure about the name attribute. According to the [instructions here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#:~:text=To%20reserve%20an,username%20is%20autofilled.) we need a user_id to create a reservation. We can't list the User's reservation with name attribute. Kindly inform me if I am missing something.

2022-10-10 18:34 UTC, huseyinbiyik commented on config/routes.rb
> +      resources :reservations
User has many reservations and reservation belongs to one User is our association type. Kindly clarify how we can meet this association with this route. I might be missing some points.

2022-10-10 18:37 UTC, felixodette commented on app/controllers/api/v1/reservations_controller.rb
> +  end
@huseyinbiyik This is to address the following requirement in the project:

When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).

2022-10-10 18:38 UTC, felixodette commented on app/controllers/api/v1/reservations_controller.rb
> +  end
Renamed the name attribute to instructions specification

2022-10-10 18:39 UTC, felixodette commented on app/controllers/api/v1/reservations_controller.rb
> +  end
@huseyinbiyik, thanks for the quick review. I've addressed this issue.

2022-10-10 18:50 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
You also need to update the Active Record table to find those column names in the reservations table.

2022-10-10 18:56 UTC, felixodette commented on config/routes.rb
> +      resources :reservations
I suspect this is what's required here then:

resources :users do
        resources :reservations

Made the change. Keen eye, missed that one.

2022-10-10 18:59 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
Here params: id is coming from the domain path and for example, if the path is api/v1/reservation/33 it will render only reservation with the id of 33. I could not find where we can use a single reservation. Kindly ask for your clarification for this part.

2022-10-10 19:18 UTC, huseyinbiyik commented on config/routes.rb
> +      resources :reservations
Happy to help you! 👍

2022-10-10 19:20 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
Okay now I see you deleted start and end date and use only only date attribute. It is fine we can go back here later.

2022-10-10 19:21 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
With your fix, now it works fine! 👍

2022-10-10 19:26 UTC, huseyinbiyik commented on app/controllers/api/v1/reservations_controller.rb
> +  end
I tested the API to create reservations. As I mentioned, you don't need this show part for this project. You can check the results below.

<img width="1440" alt="Screen Shot 2022-10-10 at 10 21 50 PM" src="https://user-images.githubusercontent.com/25887253/194938188-51b81f24-39f3-40d0-b40f-0047810b486e.png">
<img width="1440" alt="Screen Shot 2022-10-10 at 10 24 30 PM" src="https://user-images.githubusercontent.com/25887253/194938556-4adddf82-db23-4fd0-bec1-38adc4c1adfa.png">
<img width="1440" alt="Screen Shot 2022-10-10 at 10 25 24 PM" src="https://user-images.githubusercontent.com/25887253/194938703-a28f57b5-c16d-4d30-a69b-ce556ba757fe.png">

2022-10-10 19:38 UTC, felixodette commented on app/controllers/api/v1/reservations_controller.rb
> +  end
Right. Deleted the show bit.

2022-10-11 08:17 UTC, huseyinbiyik commented
Hi @felixodette ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-10-11 08:17 UTC, huseyinbiyik approved these changes
Hi @felixodette ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-10-11 08:19 UTC, merged